# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20171023_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_td',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=20)),
                ('pwd', models.CharField(default=b'', max_length=25)),
                ('tel', models.CharField(default=b'', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Car_td',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carNum', models.CharField(default=b'', max_length=12)),
                ('area', models.CharField(default=b'', max_length=20)),
                ('enterTime', models.CharField(default=b'', max_length=20)),
                ('leaveTime', models.CharField(default=b'', max_length=20)),
                ('note', models.CharField(default=b'', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vister_td',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=20)),
                ('pwd', models.CharField(default=b'', max_length=20)),
                ('pwdQ', models.CharField(default=b'', max_length=20)),
                ('pwdA', models.CharField(default=b'', max_length=20)),
                ('tel', models.CharField(default=b'', max_length=12)),
                ('carNum', models.CharField(default=b'', max_length=12)),
                ('carType', models.CharField(default=b'', max_length=20)),
                ('regTime', models.CharField(default=b'', max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
