# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carareanum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vister_td',
        ),
    ]
