# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('cars', '0005_delete_vister_td'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vister_td',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('carNum', models.CharField(default=b'', max_length=12)),
                ('carType', models.CharField(default=b'', max_length=20)),
                ('regTime', models.CharField(default=b'', max_length=25)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
