# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_vister_td'),
    ]

    operations = [
        migrations.AddField(
            model_name='vister_td',
            name='name',
            field=models.CharField(default=b'', max_length=12),
        ),
    ]
